# Generated by Django 4.1 on 2023-05-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRecords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecordsmodel',
            name='add',
            field=models.TextField(default=''),
        ),
    ]
