# Generated by Django 4.1 on 2023-05-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRecords', '0004_alter_userrecordsmodel_hire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecordsmodel',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='userrecordsmodel',
            name='lname',
        ),
        migrations.AddField(
            model_name='userrecordsmodel',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
