# Generated by Django 4.1 on 2023-05-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRecords', '0005_remove_userrecordsmodel_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecordsmodel',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
