# Generated by Django 4.1 on 2023-05-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRecords', '0007_rename_adminrecordsmodel_adminmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='add',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='age',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='contact',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
