# Generated by Django 4.1 on 2023-05-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRecords', '0008_alter_employeemodel_add_alter_employeemodel_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='hire_date',
            field=models.DateField(default=0),
        ),
    ]
