# Generated by Django 4.1 on 2023-05-18 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserRecords', '0010_alter_employeemodel_hire_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserRecords.designationmodel'),
        ),
    ]
