# Generated by Django 4.1 on 2023-05-18 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserRecords', '0012_alter_employeemodel_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserRecords.designationmodel'),
        ),
    ]
