# Generated by Django 4.1 on 2023-05-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRecords', '0015_alter_employeemodel_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designationmodel',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
