# Generated by Django 4.1 on 2023-05-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRecords', '0017_contactnosmodel_remove_employeemodel_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelephoneNosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teleno', models.IntegerField()),
            ],
        ),
    ]
