# Generated by Django 4.1 on 2023-05-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRecords', '0018_telephonenosmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='tele',
            field=models.ManyToManyField(to='UserRecords.telephonenosmodel'),
        ),
    ]
