# Generated by Django 4.1 on 2023-06-16 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserRecords', '0021_alter_employeemodel_teles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='contact',
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='teles',
            field=models.ManyToManyField(blank=True, related_name='employees', to='UserRecords.telephonenosmodel'),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserRecords.contactnosmodel'),
        ),
    ]
