# Generated by Django 4.1 on 2023-06-16 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserRecords', '0022_remove_employeemodel_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='UserRecords.contactnosmodel'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UserRecords.designationmodel'),
        ),
    ]
